# The URL the site will be built for
base_url = "https://firman-qs.github.io/"
title = "fqsss"
description = "fqss is fqss"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
# Put all your custom variables here
toc = true
theme = "toggle"
mathjax = true
mathjax_dollar_inline_enable = true
katex_enable = true
katex_auto_render = true
dynamic_note = true
fancy_code = true
socials = [
  # Configure socials here
  { name = "twitter", url = "https://twitter.com/firmanqs_", icon = "twitter" },
  { name = "github", url = "https://github.com/firman-qs/", icon = "github" },
  { name = "rss", url = "/atom.xml", icon = "rss" },
]
menu = [
  { name = "/home", url = "/", weight = 1 },
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 },
  { name = "/tags", url = "/tags", weight = 2 },
]

stylesheets = [
  "style.css",
  "syntax-theme-dark.css",
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

